spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/directmessage
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  jwt-expiration: 33333333333333333
  jwt-refresh-expiration: 99999999999999999

aws:
  S3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
  region: ${AWS_REGION}
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}

user:
  status:
    inactive-threshold-minutes: 30

message:
  edit-minutes: 5
  delete-minutes: 5